//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mediateur.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResAdmin {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResAdmin() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mediateur.Resources.ResAdmin", typeof(ResAdmin).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انواع الصنف.
        /// </summary>
        public static string DataTableItemsType {
            get {
                return ResourceManager.GetString("DataTableItemsType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Reslution.
        /// </summary>
        public static string lbl {
            get {
                return ResourceManager.GetString("lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Us.
        /// </summary>
        public static string lblCallUs {
            get {
                return ResourceManager.GetString("lblCallUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        public static string lblCategoryName {
            get {
                return ResourceManager.GetString("lblCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string lblDescription {
            get {
                return ResourceManager.GetString("lblDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string lblEmail {
            get {
                return ResourceManager.GetString("lblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Your name.
        /// </summary>
        public static string lblEnterYourname {
            get {
                return ResourceManager.GetString("lblEnterYourname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Your Review Subjects.
        /// </summary>
        public static string lblEnterYourReviewSubjects {
            get {
                return ResourceManager.GetString("lblEnterYourReviewSubjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.A.Q.
        /// </summary>
        public static string lblFAQ {
            get {
                return ResourceManager.GetString("lblFAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For You.
        /// </summary>
        public static string lblForYou {
            get {
                return ResourceManager.GetString("lblForYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string lblGender {
            get {
                return ResourceManager.GetString("lblGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gpu.
        /// </summary>
        public static string lblGpu {
            get {
                return ResourceManager.GetString("lblGpu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HardDisk.
        /// </summary>
        public static string lblHardDisk {
            get {
                return ResourceManager.GetString("lblHardDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string lblImage {
            get {
                return ResourceManager.GetString("lblImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Name.
        /// </summary>
        public static string lblItemName {
            get {
                return ResourceManager.GetString("lblItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item Type.
        /// </summary>
        public static string lblItemType {
            get {
                return ResourceManager.GetString("lblItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Type Name.
        /// </summary>
        public static string lblItemTypeName {
            get {
                return ResourceManager.GetString("lblItemTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to laptop.
        /// </summary>
        public static string lbllaptop {
            get {
                return ResourceManager.GetString("lbllaptop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mediateur.
        /// </summary>
        public static string lblMediateur {
            get {
                return ResourceManager.GetString("lblMediateur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book via WhatsApp and collect from the nearest branch.
        ///More than 50 branches are available .
        /// </summary>
        public static string lblMessageUs {
            get {
                return ResourceManager.GetString("lblMessageUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string lblName {
            get {
                return ResourceManager.GetString("lblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now Products.
        /// </summary>
        public static string lblNowProducts {
            get {
                return ResourceManager.GetString("lblNowProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original.
        /// </summary>
        public static string lblOriginal {
            get {
                return ResourceManager.GetString("lblOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os.
        /// </summary>
        public static string lblOs {
            get {
                return ResourceManager.GetString("lblOs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string lblPrice {
            get {
                return ResourceManager.GetString("lblPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor.
        /// </summary>
        public static string lblProcessor {
            get {
                return ResourceManager.GetString("lblProcessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produc.
        /// </summary>
        public static string lblProduct {
            get {
                return ResourceManager.GetString("lblProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نكهة السودان و العرب في كل لمسة.
        /// </summary>
        public static string lblProductMessage {
            get {
                return ResourceManager.GetString("lblProductMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Price.
        /// </summary>
        public static string lblPurchasePrice {
            get {
                return ResourceManager.GetString("lblPurchasePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ram Size.
        /// </summary>
        public static string lblRamSize {
            get {
                return ResourceManager.GetString("lblRamSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string lblRating {
            get {
                return ResourceManager.GetString("lblRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommendations For You.
        /// </summary>
        public static string lblRecommendationsForYou {
            get {
                return ResourceManager.GetString("lblRecommendationsForYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RelatedProducts.
        /// </summary>
        public static string lblRelatedProducts {
            get {
                return ResourceManager.GetString("lblRelatedProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Title.
        /// </summary>
        public static string lblReviewTitle {
            get {
                return ResourceManager.GetString("lblReviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Price.
        /// </summary>
        public static string lblSalesPrice {
            get {
                return ResourceManager.GetString("lblSalesPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Reslution.
        /// </summary>
        public static string lblScreenReslution {
            get {
                return ResourceManager.GetString("lblScreenReslution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Size.
        /// </summary>
        public static string lblScreenSize {
            get {
                return ResourceManager.GetString("lblScreenSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Home Page.
        /// </summary>
        public static string lblShowHomePage {
            get {
                return ResourceManager.GetString("lblShowHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Your Review.
        /// </summary>
        public static string lblSubmitYourReview {
            get {
                return ResourceManager.GetString("lblSubmitYourReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string lblVideo {
            get {
                return ResourceManager.GetString("lblVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string lblWeight {
            get {
                return ResourceManager.GetString("lblWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrire Your Testimonial Here.
        /// </summary>
        public static string lblWrireYourTestimonialHere {
            get {
                return ResourceManager.GetString("lblWrireYourTestimonialHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Review.
        /// </summary>
        public static string lblWriteReview {
            get {
                return ResourceManager.GetString("lblWriteReview", resourceCulture);
            }
        }
    }
}
